(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
	(define (iter expr)
		(if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
		)
	(iter (readExpr))    
)
(define (range start end raise)
	(define (helper help)
		(cond
			((or
				(and(> raise 0) (< help end)) 
				(and(< raise 0) (> help end))) 
				(cons help (helper (+ raise help))) 
			)
			(else nil)
			)
		)
	(helper start)
)
(define (for-loop makeList pass) 
	(cond
		((null? makeList)nil) 
		(else (begin
			(pass (car makeList))
			(for-loop (cdr makeList) pass) ;
		))
	)
)